Fix AddCommandParserTest
AY2324S1-CS2103T-W12-2/tp pull request #62
Opened 2023-10-17 15:53 UTC by Kevin-Liusx

Fix parse_allFieldsPresent_success test case
Found the issue for parse_optionalFieldsMissing_success test case

2023-10-17 16:15 UTC, Kevin-Liusx commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +import static seedu.address.logic.commands.CommandTestUtil.*;
Thanks for reminding. Will change at end.

2023-10-18 05:05 UTC, jibtaf requested changes

2023-10-18 05:05 UTC, jibtaf commented on src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
> +import static seedu.address.logic.parser.CliSyntax.*;
Should avoid wildcard import

2023-10-18 07:31 UTC, jibtaf commented
lgtm

2023-10-18 07:31 UTC, merged